services:
  db:
    build: ./data/
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql/
    environment:
      - MARIADB_ROOT_PASSWORD=bar
  web:
    build: .
    ports:
      - "80:5000"
    environment:
      - HOST=db
    depends_on:
      - db
volumes:
  db_data:
